arch: amd64

language: java

jdk:
  - oraclejdk11

install: skip

before_script:
  - cd ${TRAVIS_BUILD_DIR}/intellij-recon
  - chmod +x ./gradlew

script:
  - java --version
  - ./gradlew :generateAll
  - ./gradlew :test
